version: 2.1
orbs:
  terraform: circleci/terraform@1.1.1
  python: circleci/python@1.3.2

jobs:
  render-test-files:
    executor: python/3.9.0
    steps:
    - checkout
    - python/load-cache
    - python/install-deps:
        pip-dependency-file: ./.test/requirements.txt
        pkg-manager: pip      
    - python/save-cache
    - run: |
        cd ./test
        python ./render_template.py
    - persist_to_workspace:
        root: /tmp/
        paths:
          - ./test/rendered/*
  tf-validate:
    executor: terraform/default
    context: tf-testing
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          cp /tmp/workspace/rendered/* .
      - terraform/fmt
      - terraform/validate
        
  tf-test-deploy:
    executor: terraform/default
    context: tf-testing
    steps:
      - run: cp ./rendered/* ..
      - terraform/plan
      - terraform/apply
      - terraform/destroy

workflows:
  version: 2
  main:
    jobs:
      - render-test-files
      - tf-validate
      - tf-test-deploy:
          filters:
            branches:
              only:
                - master
                - tfmoduletesting #debug

